
// This file has been generated by the GUI designer. Do not modify.
namespace InterfazGrupo15
{
	public partial class Window2
	{
		private global::Gtk.VBox vbox25;

		private global::Gtk.VBox vbox26;

		private global::Gtk.HBox hbox20;

		private global::Gtk.Label Label;

		private global::Gtk.Entry entry21;

		private global::Gtk.HBox hbox22;

		private global::Gtk.Label label17;

		private global::Gtk.Entry entry23;

		private global::Gtk.HBox hbox24;

		private global::Gtk.Label label19;

		private global::Gtk.Entry entry25;

		private global::Gtk.VBox vbox28;

		private global::Gtk.HBox hbox26;

		private global::Gtk.Label label21;

		private global::Gtk.Entry entry28;

		private global::Gtk.HBox hbox28;

		private global::Gtk.Label label23;

		private global::Gtk.Entry entry30;

		private global::Gtk.HBox hbox30;

		private global::Gtk.Label label27;

		private global::Gtk.ComboBox combobox3;

		private global::Gtk.VBox vbox30;

		private global::Gtk.HBox hbox32;

		private global::Gtk.Label label25;

		private global::Gtk.Entry entry32;

		private global::Gtk.HBox hbox34;

		private global::Gtk.Button button9;

		private global::Gtk.Button button7;

		private global::Gtk.Label label29;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget InterfazGrupo15.Window2
			this.Name = "InterfazGrupo15.Window2";
			this.Title = global::Mono.Unix.Catalog.GetString("Window2");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child InterfazGrupo15.Window2.Gtk.Container+ContainerChild
			this.vbox25 = new global::Gtk.VBox();
			this.vbox25.Name = "vbox25";
			this.vbox25.Spacing = 6;
			// Container child vbox25.Gtk.Box+BoxChild
			this.vbox26 = new global::Gtk.VBox();
			this.vbox26.Name = "vbox26";
			this.vbox26.Spacing = 6;
			// Container child vbox26.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.Label = new global::Gtk.Label();
			this.Label.Name = "Label";
			this.Label.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.hbox20.Add(this.Label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.Label]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.entry21 = new global::Gtk.Entry();
			this.entry21.CanFocus = true;
			this.entry21.Name = "entry21";
			this.entry21.IsEditable = true;
			this.entry21.InvisibleChar = '●';
			this.hbox20.Add(this.entry21);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.entry21]));
			w2.Position = 1;
			this.vbox26.Add(this.hbox20);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.hbox20]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox26.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Apodo");
			this.hbox22.Add(this.label17);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.label17]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.entry23 = new global::Gtk.Entry();
			this.entry23.CanFocus = true;
			this.entry23.Name = "entry23";
			this.entry23.IsEditable = true;
			this.entry23.InvisibleChar = '●';
			this.hbox22.Add(this.entry23);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.entry23]));
			w5.Position = 1;
			this.vbox26.Add(this.hbox22);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.hbox22]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox26.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Telefono");
			this.hbox24.Add(this.label19);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.label19]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.entry25 = new global::Gtk.Entry();
			this.entry25.CanFocus = true;
			this.entry25.Name = "entry25";
			this.entry25.IsEditable = true;
			this.entry25.InvisibleChar = '●';
			this.hbox24.Add(this.entry25);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.entry25]));
			w8.Position = 1;
			this.vbox26.Add(this.hbox24);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.hbox24]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox25.Add(this.vbox26);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.vbox26]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.vbox28 = new global::Gtk.VBox();
			this.vbox28.Name = "vbox28";
			this.vbox28.Spacing = 6;
			// Container child vbox28.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Contraseña");
			this.hbox26.Add(this.label21);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.label21]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.entry28 = new global::Gtk.Entry();
			this.entry28.CanFocus = true;
			this.entry28.Name = "entry28";
			this.entry28.IsEditable = true;
			this.entry28.InvisibleChar = '●';
			this.hbox26.Add(this.entry28);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.entry28]));
			w12.Position = 1;
			this.vbox28.Add(this.hbox26);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hbox26]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.hbox28 = new global::Gtk.HBox();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Mail");
			this.hbox28.Add(this.label23);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.label23]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.entry30 = new global::Gtk.Entry();
			this.entry30.CanFocus = true;
			this.entry30.Name = "entry30";
			this.entry30.IsEditable = true;
			this.entry30.InvisibleChar = '●';
			this.hbox28.Add(this.entry30);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.entry30]));
			w15.Position = 1;
			this.vbox28.Add(this.hbox28);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hbox28]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.hbox30 = new global::Gtk.HBox();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Tipo");
			this.hbox30.Add(this.label27);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.label27]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.combobox3 = global::Gtk.ComboBox.NewText();
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("alumno"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("personal"));
			this.combobox3.Name = "combobox3";
			this.combobox3.Active = 0;
			this.hbox30.Add(this.combobox3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.combobox3]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox28.Add(this.hbox30);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hbox30]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox25.Add(this.vbox28);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.vbox28]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.vbox30 = new global::Gtk.VBox();
			this.vbox30.Name = "vbox30";
			this.vbox30.Spacing = 6;
			// Container child vbox30.Gtk.Box+BoxChild
			this.hbox32 = new global::Gtk.HBox();
			this.hbox32.Name = "hbox32";
			this.hbox32.Spacing = 6;
			// Container child hbox32.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Carrera/ Cargo");
			this.hbox32.Add(this.label25);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.label25]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox32.Gtk.Box+BoxChild
			this.entry32 = new global::Gtk.Entry();
			this.entry32.CanFocus = true;
			this.entry32.Name = "entry32";
			this.entry32.IsEditable = true;
			this.entry32.InvisibleChar = '●';
			this.hbox32.Add(this.entry32);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.entry32]));
			w22.Position = 1;
			this.vbox30.Add(this.hbox32);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.hbox32]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox30.Gtk.Box+BoxChild
			this.hbox34 = new global::Gtk.HBox();
			this.hbox34.Name = "hbox34";
			this.hbox34.Spacing = 6;
			// Container child hbox34.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString("Atras");
			this.hbox34.Add(this.button9);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.button9]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox34.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString("Crear Usuario");
			this.hbox34.Add(this.button7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.button7]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox30.Add(this.hbox34);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.hbox34]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox25.Add(this.vbox30);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.vbox30]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Mensaje");
			this.vbox25.Add(this.label29);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.label29]));
			w28.PackType = ((global::Gtk.PackType)(1));
			w28.Position = 3;
			w28.Expand = false;
			w28.Fill = false;
			this.Add(this.vbox25);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.button7.Clicked += new global::System.EventHandler(this.OnButton7Clicked);
		}
	}
}
